apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serveurflex-ingress
  namespace: serverflex
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    argocd.argoproj.io/health-ignore: "true"
spec:
  ingressClassName: nginx-internal
  rules:
  - host: frontend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: backend.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
  